import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/shared/components/layout/Footer";
import { Header } from "@/shared/components/layout/Header";
import { I18nProvider } from "@/providers/I18nProvider";

export const metadata: Metadata = {
  title: "YATA YOTA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <I18nProvider>
          <Header/>
          {children}
          <Footer/>
        </I18nProvider>
      </body>
    </html>
  );
}





